[context.production.environment]
  REACT_APP_SENTRY_DSN_FRONTEND = "https://f389e257602342899d1639d9c0c7f476@o370480.ingest.sentry.io/6194602"
  REACT_APP_SENTRY_CURRENT_RELEASE_NAME = ""
  REACT_APP_SENTRY_ENVIRONMENT = "production"
  REACT_APP_SENTRY_SAMPLERATE = "1"
  REACT_APP_PASSPORT_API_ENDPOINT_HOSTNAME = "api.xsyn.io"
  REACT_APP_PASSPORT_METAMASK_SIGN_MESSAGE = ""
  REACT_APP_BYPASS_WHITELIST = "false"
  REACT_APP_BATTLE_ARENA_LINK = "https://play.supremacy.game"
  REACT_APP_NFT_CONTRACT_ADDRESS = "0x24447528deb67F492Af4AF7fb3Afb89476e0bCfD"
  REACT_APP_NFT_STAKING_CONTRACT_ADDRESS = "0x6476dB7cFfeeBf7Cc47Ed8D4996d1D60608AAf95"
  REACT_APP_SUPS_CONTRACT_ADDRESS = "0xc99cFaA8f5D9BD9050182f29b83cc9888C5846C4"
  REACT_APP_USDC_CONTRACT_ADDRESS = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
  REACT_APP_BUSD_CONTRACT_ADDRESS = "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
  REACT_APP_ETH_SCAN_SITE = "etherscan.io"
  REACT_APP_BSC_SCAN_SITE = "bscscan.com"
  REACT_APP_ETHEREUM_CHAIN_ID = "1"
  REACT_APP_BINANCE_CHAIN_ID = "56"
  REACT_APP_PURCHASE_ADDRESS = "0x52b38626D3167e5357FE7348624352B7062fE271"
  REACT_APP_WITHDRAW_ADDRESS = "0x6476dB7cFfeeBf7Cc47Ed8D4996d1D60608AAf95"
  REACT_APP_REDEEM_ADDRESS = "0x0"
  REACT_APP_WALLET_CONNECT_RPC = "1375aa321ac8ac6cfba6aa9c"

[context.staging.environment]
  REACT_APP_SENTRY_DSN_FRONTEND = "https://f389e257602342899d1639d9c0c7f476@o370480.ingest.sentry.io/6194602"
  REACT_APP_SENTRY_CURRENT_RELEASE_NAME = ""
  REACT_APP_SENTRY_ENVIRONMENT = "staging"
  REACT_APP_SENTRY_SAMPLERATE = "1"
  REACT_APP_PASSPORT_API_ENDPOINT_HOSTNAME = "staging-passport.xsyn.io"
  REACT_APP_PASSPORT_METAMASK_SIGN_MESSAGE = ""
  REACT_APP_BYPASS_WHITELIST = "false"
  REACT_APP_BATTLE_ARENA_LINK = "https://staging.deltaforce.supremacy.game"
  