[context.production.environment]
  REACT_APP_SENTRY_DSN_FRONTEND = "https://f389e257602342899d1639d9c0c7f476@o370480.ingest.sentry.io/6194602"
  REACT_APP_SUPREMACY_WORLD_WEB = "https://www.supremacyworld.com"
  REACT_APP_SENTRY_CURRENT_RELEASE_NAME = ""
  REACT_APP_SENTRY_ENVIRONMENT = "production"
  REACT_APP_SENTRY_SAMPLERATE = "1"
  REACT_APP_PASSPORT_API_ENDPOINT_HOSTNAME = "api.xsyn.io"
  REACT_APP_PASSPORT_API_SUPREMACY ="passport.supremacy.game"
  REACT_APP_PASSPORT_METAMASK_SIGN_MESSAGE = ""
  REACT_APP_BYPASS_WHITELIST = "false"
  REACT_APP_BATTLE_ARENA_LINK = "https://play.supremacy.game"
  REACT_APP_NFT_CONTRACT_ADDRESS = "0x651D4424F34e6e918D8e4D2Da4dF3DEbDAe83D0C"
  REACT_APP_NFT_STAKING_CONTRACT_ADDRESS = "0x6476dB7cFfeeBf7Cc47Ed8D4996d1D60608AAf95"
  REACT_APP_SUPS_CONTRACT_ADDRESS = "0xc99cFaA8f5D9BD9050182f29b83cc9888C5846C4"
  REACT_APP_SUPS_CONTRACT_ADDRESS_ETH = "0xCF39360b26a7E54f6c456E69640671Fc5e774FA2"
  REACT_APP_USDC_CONTRACT_ADDRESS = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
  REACT_APP_BUSD_CONTRACT_ADDRESS = "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
  REACT_APP_ETH_SCAN_SITE = "etherscan.io"
  REACT_APP_BSC_SCAN_SITE = "bscscan.com"
  REACT_APP_ETHEREUM_CHAIN_ID = "1"
  REACT_APP_BINANCE_CHAIN_ID = "56"
  REACT_APP_PURCHASE_ADDRESS = "0x52b38626D3167e5357FE7348624352B7062fE271"
  REACT_APP_WITHDRAW_ADDRESS = "0x6476dB7cFfeeBf7Cc47Ed8D4996d1D60608AAf95"
  REACT_APP_REDEEM_ADDRESS = "0x0"
  REACT_APP_WALLET_CONNECT_RPC = "1375aa321ac8ac6cfba6aa9c"
  REACT_APP_FARM_CONTRACT_ADDRESS = "0x768F80c7B256cf921F8C557CeC9D0Bd97766f253"
  REACT_APP_PANCAKE_POOL_ADDRESS = "0x10ED43C718714eb63d5aA57B78B54704E256024E"
  REACT_APP_LP_TOKEN_ADDRESS = "0x3d4a5844e19dbe4bb5c77eaee06e56289a0d83b1"
  REACT_APP_WRAPPED_BNB_ADDRESS = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
  REACT_APP_PANCAKE_SWAP_ADDRESS = "pancakeswap.finance"
  REACT_APP_FACEBOOK_APP_ID="558079075693199"
  REACT_APP_GOOGLE_ID="467953368642-8cobg822tej2i50ncfg4ge1pm4c5v033.apps.googleusercontent.com"
  REACT_APP_PASSPORT_ENVIRONMENT= "production"
  REACT_APP_CAPTCHA_SITE_KEY="6c84c39b-975f-4c12-879e-f14b3dd7bdba"
  REACT_APP_INFURA_ETHEREUM_NODE="https://mainnet.infura.io/v3/38ee3b4f0d5a4adfb02fe1ca64645e22"


[context.staging.environment]
  REACT_APP_SUPREMACY_WORLD_WEB = "https://develop--supremacyworld.netlify.app"
  REACT_APP_SENTRY_DSN_FRONTEND = "https://f389e257602342899d1639d9c0c7f476@o370480.ingest.sentry.io/6194602"
  REACT_APP_SENTRY_CURRENT_RELEASE_NAME = ""
  REACT_APP_SENTRY_ENVIRONMENT = "staging"
  REACT_APP_SENTRY_SAMPLERATE = "1"
  REACT_APP_PASSPORT_API_ENDPOINT_HOSTNAME = "api.xsyn.dev"
  REACT_APP_PASSPORT_METAMASK_SIGN_MESSAGE = ""
  REACT_APP_BYPASS_WHITELIST = "false"
  REACT_APP_BATTLE_ARENA_LINK = "https://staging.supremacygame.dev"
  REACT_APP_AVANT_API_ENDPOINT = "v3-staging.supremacy-api.avantdata.com:3001"
  REACT_APP_FACEBOOK_APP_ID="558079075693199"
  REACT_APP_GOOGLE_ID="467953368642-8cobg822tej2i50ncfg4ge1pm4c5v033.apps.googleusercontent.com"
  REACT_APP_PASSPORT_API_SUPREMACY ="passport.supremacygame.dev"
  REACT_APP_PASSPORT_ENVIRONMENT= "staging"
  REACT_APP_CAPTCHA_SITE_KEY="d44828b7-471d-4da3-aa8d-173a7dea7da9"
